name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-27"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDZhYTNiYjYtYTBhMC00Yzg3LTkzZDUtYTI2ZDE1Y2UzYzY5IiwidGVuYW50X2lkIjoiODZlNTk1ZTMzN2EwODEwOGM2YTJlNjgzY2JhNjFhNTExNzEwNWEwYmIwOWUwMmMwYjVhM2Y4NzNiYTc1NDliNCIsImludGVybmFsX3NlY3JldCI6IjVmNzJlMzBlLWVkNjgtNGI1ZC05YThlLTMzY2Y5YjIzZDU3NyJ9.9VOfP6iGuqgDq8ROAmRU4n7dc4U5MlZ4CUXitwe1QkY"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1