import type { Metadata } from "next";

import {Libre_Baskerville} from "next/font/google"
import "./globals.css";
import { RecoilContextProvider } from "@/lib/RecoilContextProvider";
import { AppBar } from "@/components/AppBar";
// import Footer from "@/components/Footer";


const libre = Libre_Baskerville({
  weight: "400",
  subsets: ["latin"]
  
})


export const metadata: Metadata = {
  title: "It's what i think",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre.className} antialiased bg-[#000000] text-white `}
      >
        
        <AppBar />
        <RecoilContextProvider>

        {children}

        </RecoilContextProvider>
      
        
      </body>
    </html>
  );
}
